config/urls.py
# config/urls.py

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('posts/', include('portfolio.urls')),
]

portfolio/urls.py
from . import views
from django.urls import path

app_name = "portfolio"

urlpatterns = [
    path('',views.home_page_view, name='home'),
    path('home', views.home_page_view, name='home'),
    path('projetos', views.projetos_page_view, name='projetos'),
    path('licenciatura', views.licenciatura_page_view, name='licenciatura'),
    path('blog', views.blog_page_view, name='blog'),
    path('nova', views.nova_page_view, name='nova'),
    path('edita/<int:post_id>', views.edita_page_view, name='edita'),
    path('apaga/<int:post_id>', views.apaga_page_view, name='apaga'),
    path('quizz', views.quizz_page_view, name='quizz'),
]

portfolio/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    autor = models.CharField(max_length=30)
    data = models.DateTimeField(auto_now_add = True)
    titulo = models.CharField(max_length=30)
    descricao = models.CharField(max_length=255)

    def __str__(self):
        return f'"{self.titulo}" por {self.autor}'

class Professor(models.Model):
    nome = models.CharField(max_length= 64)
    imagem = models.ImageField(upload_to="portfolio/static/portfolio/images/professores", null=True, blank=True)

    def __str__(self):
        return self.nome

class Cadeira(models.Model):
    nome = models.CharField(max_length=30)
    ects = models.IntegerField(default=1)
    ano = models.IntegerField(default=1)
    semestre = models.IntegerField(default=1)
    topicos = models.CharField(max_length=100)
    ranking = models.IntegerField(default=1)
    imagem = models.ImageField(upload_to="portfolio/static/portfolio/images/cadeira", null=True, blank=True)
    professor = models.ForeignKey(Professor, on_delete=models.PROTECT, related_name="Cadeiras")

    def __str__(self):
        return self.nome

class Projeto(models.Model):
    titulo = models.CharField(max_length=30)
    descricao = models.CharField(max_length=500)
    imagem = models.ImageField(upload_to="portfolio/static/portfolio/images/projetos", null=True, blank=True)
    cadeira = models.ForeignKey(Cadeira, on_delete=models.PROTECT, related_name="Projetos")

    def __str__(self):
        return self.titulo

class PontuacaoQuizz(models.Model):
    nome = models.CharField(max_length=30)
    pontuacao = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.nome} : {self.pontuacao} pontos'

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        widgets = {
            'autor': forms.TextInput(attrs={'class': 'form-autor'}),
            'titulo': forms.TextInput(attrs={'class': 'form-titulo'}),
            'descricao': forms.TextInput(attrs={'class': 'form-descricao'}),
        }

portfolio/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from matplotlib import pyplot as plt

import datetime

from .forms import PostForm
from .models import Post
from .models import Cadeira
from .models import Projeto
from .models import PontuacaoQuizz

# Create your views here.


def home_page_view(request):
    agora = datetime.datetime.now()
    local = 'Lisboa'
    topicos = ['HTML', 'CSS', 'Python', 'Django', 'JavaScript']

    context = {
        'hora': agora.hour,
        'local': local,
        'topicos': topicos,
    }

    return render(request, 'portfolio/home.html', context)


def projetos_page_view(request):
    context = {'projetos': Projeto.objects.all()}
    return render(request, 'portfolio/projetos.html', context)


def licenciatura_page_view(request):
    context = {'cadeiras': Cadeira.objects.all()}
    return render(request, 'portfolio/licenciatura.html', context)


def blog_page_view(request):
    context = {'posts': Post.objects.all()}

    return render(request, 'portfolio/blog.html', context)


def nova_page_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form}

    return render(request, 'portfolio/nova.html', context)


def edita_page_view(request, post_id):
    post = Post.objects.get(pk=post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:blog'))

    context = {'form': form, 'post_id': post_id}

    return render(request, 'portfolio/edita.html', context)


def apaga_page_view(request, post_id):
    Post.objects.get(id=post_id).delete()
    return HttpResponseRedirect(reverse('portfolio:blog'))


def pontuacao_quizz(request):
    score = 0
    if request.POST['questao1'] == 'b':
        score += 1

    if request.POST['questao2'] == 'b':
        score += 1

    if request.POST['questao3'] == 'a':
        score += 1

    return score


def quizz_page_view(request):
    if request.method == 'POST':
        n = request.POST['nome']
        p = pontuacao_quizz(request)
        r = PontuacaoQuizz(nome=n, pontuacao=p)
        r.save()
        desenha_grafico_resultados(request)
    return render(request, 'portfolio/quizz.html')


def desenha_grafico_resultados(request):
    resultados = sorted(PontuacaoQuizz.objects.all(), key=lambda objeto: objeto.pontuacao, reverse=True)

    lista_nomes = []
    lista_pontuacao = []

    for pessoa in resultados:
        lista_nomes.append(pessoa.nome)
        lista_pontuacao.append(pessoa.pontuacao)

    plt.barh(lista_nomes, lista_pontuacao)
    plt.savefig('portfolio/static/portfolio/images/grafico.png', bbox_inches='tight')

portfolio/templates/portfolio/blog.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <style>
        main{
            {% load static %}
            background-image: url("{% static 'portfolio/images/blog.jpg' %}");
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: cover;
        }

        h3{
            color: white;
        }
    </style>
    <section>
        <h3>Blog</h3>
        <div style="width: 100%; height: 100px">
            <a href="{% url 'portfolio:nova' %}" class="new_post">Novo Post</a>
        </div>
        <div class="post_body">

            <div class="posts_container">
                {% for post in posts %}
                    <div class="post">
                        <div class="post-inicial">
                            <div>
                                <h2>{{ post.titulo }}</h2>
                                <p>{{ post.autor }}</p>
                                <a href="{% url 'portfolio:edita' post.id %}" class="botao_editar">
                                   <button>
                                        <i class="material-icons" style="color:white">edit</i>
                                   </button>
                                </a>
                            </div>
                        </div>
                        <div class="post-overlay"></div>
                        <div class="post-content">
                            <h2>{{ post.titulo }}</h2>
                            <p>{{ post.descricao }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>

    </section>


{% endblock %}

portfolio/templates/portfolio/edita.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h3>Novo post</h3>
    <form action="{% url 'portfolio:edita' post_id %}" method="POST" autocomplete="off">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:blog' %}" role="button" class="btn">Cancelar</a>
        <input type="submit" value="Gravar" class="btn" >
        <a href="{% url 'portfolio:apaga' post_id %}" role="button" class="btn">Apagar</a>
    </form>

{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <section class="hero-image">
        {% load static %}
        <video src="{% static 'portfolio/images/HeroImage.mp4' %}" muted loop autoplay></video>
        <div class="overlay"></div>
        <div class="text-hero-image">
            <h2>O meu portfolio</h2>
            <p>Olá sou o Diogo e sou estudande de engenharia informatica</p>
            <a href="#labs">Sobre Mim</a>
        </div>
    </section>


    <h3>Titulo</h3>
    <p>texto texto texto texto texto texto texto </p>

    {% load static %}
    <img src="{% static 'portfolio/images/image.jpg' %}">
{% endblock %}

portfolio/templates/portfolio/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="pt">
<head>
    <title>Lab 5</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    {% load static %}
    <link rel="stylesheet" href="{% static 'portfolio/css/layout.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/licenciatura.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/home.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/blog.css' %}">
    <link rel="stylesheet" href="{% static 'portfolio/css/projetos.css' %}">


</head>
<body>
    <header>
        <div>Diogo Cerqueira</div>
        <nav>
            <a href="{% url 'portfolio:home' %}">Home</a>
            <a href="{% url 'portfolio:licenciatura' %}">Licenciatura</a>
            <a href="{% url 'portfolio:projetos' %}">Projetos</a>
            <a href="{% url 'portfolio:blog' %}">Blog</a>
            <a href="{% url 'portfolio:quizz' %}">Quizz</a>
        </nav>
    </header>
    <main>
        {% block main %}

        {% endblock main %}
    </main>
    <footer>
        ULHT, 2022
    </footer>
</body>
</html>

portfolio/templates/portfolio/licenciatura.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<section>
        <h3>Licenciatura</h3>
        <div class="cadeira_container">
            {% for cadeira in cadeiras %}
                <div class="cadeira">
                    <div class="cadeira-img">
                        {% load static %}
                        <img src="{{ cadeira.imagem.url }}">
                    </div>
                    <div class="cadeira-body">
                        <span class="cadeira-nome"> {{ cadeira.nome}} </span>
                        <span class="cadeira-ects">{{ cadeira.ects }} ECTS</span>
                        <h4>
                            {{ cadeira.topicos }}
                        </h4>
                        <p>
                            {{ cadeira.ano }} ano {{ cadeira.semestre }} semestre
                        </p>
                        <p>
                            {% if cadeira.ranking == 1 %}
                                ⭐
                            {% elif cadeira.ranking == 2 %}
                                ⭐⭐
                            {% elif cadeira.ranking == 3 %}
                                ⭐⭐⭐
                            {% elif cadeira.ranking == 4 %}
                                ⭐⭐⭐⭐
                            {% elif cadeira.ranking == 5 %}
                                ⭐⭐⭐⭐⭐
                            {% endif %}
                        </p>
                        <div class="cadeira-prof">
                            <img src="{{ cadeira.professor.imagem}}">
                            <div class="prof-info">
                                <h5>{{ cadeira.professor.nome }}</h5>
                            </div>
                        </div>
                    </div>

                </div>
            {% endfor %}
        </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/nova.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <h3>Novo post</h3>
    <form method="post" action="" autocomplete="off">
        {% csrf_token %}

        {{ form.as_p }}
        <input type="submit" value="Gravar">

    </form>

{% endblock %}

portfolio/templates/portfolio/projetos.html
{% extends 'portfolio/layout.html' %}

{% block main %}
	<section>
        <h3>Projetos</h3>
        <div class="projeto_container">
                {% for projeto in projetos %}
                    <div class="projeto">
                        <div class="projeto-img">
                            {% load static %}
                            <img src="{{ projeto.imagem.url }}">
                        </div>
                        <div class="projeto-body">
                            <span class="projeto-cadeira-nome"> {{ projeto.cadeira.nome }} </span>
                            <h4>
                                {{ projeto.titulo }}
                            </h4>
                            <p>
                                {{ projeto.descricao }}
                            </p>

                            <div class="projeto-prof">
                                <img src="{{ projeto.cadeira.professor.imagem}}">
                                <div class="prof-info">
                                    <h5>{{ projeto.cadeira.professor.nome }}</h5>
                                </div>
                            </div>
                        </div>

                    </div>
                {% endfor %}
            </div>
    </section>
{% endblock %}

portfolio/templates/portfolio/quizz.html
{% extends 'portfolio/layout.html' %}

{% block main %}
    <section>
        <h3>Quizz</h3>
        <form method="post" action="" autocomplete="off" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <legend>Programação Web</legend>
                <label for="nome">Nome:</label>
                <input type="text" id="nome" name="nome" placeholder="Insira o nome" autofocus><br><br>
                <h1>Pergunta 1:</h1>
                <label>Qual o significado de HTML?</label><br><br>
                <input type="radio" id="1a" name="questao1" value="a">
                <label for="1a"> Home Tool Markup Language </label><br>
                <input type="radio" id="1b" name="questao1" value="b">
                <label for="1b"> Hyper Text Markup Language</label><br>
                <input type="radio" id="1c" name="questao1" value="c">
                <label for="1c"> Hyperlinks and Text Markup Language</label><br><br>

                <h1>Pergunta 2:</h1>
                <label>Qual dos seguintes atributos especifica um texto alternativo para uma imagem, se a imagem não puder ser exibida? </label><br><br>
                <input type="radio" id="2a" name="questao2" value="a">
                <label for="2a"> src </a> </label><br>
                <input type="radio" id="2b" name="questao2" value="b">
                <label for="2b"> alt </label><br>
                <input type="radio" id="2c" name="questao2" value="c">
                <label for="2c"> title</label><br>
                <input type="radio" id="2d" name="questao2" value="d">
                <label for="2d"> legend </label><br><br>

                <h1>Pergunta 3:</h1>
                <label>Qual tipo de entrada define uma barra deslizante? </label><br><br>
                <input type="radio" id="3a" name="questao3" value="a">
                <label for="3a"> range </a> </label><br>
                <input type="radio" id="3b" name="questao3" value="b">
                <label for="3b"> slider </label><br>
                <input type="radio" id="3c" name="questao3" value="c">
                <label for="3c"> search</label><br>
                <input type="radio" id="3d" name="questao3" value="d">
                <label for="3d"> controls </label><br><br>

                <input type="submit" value="Submit">
            </fieldset>

        </form>

        {% load static %}
        <img src="{% static 'portfolio/images/grafico.png' %}" alt="" >
    </section>
{% endblock %}